name: Test Components

on:
  push:
    branches:
      - master
    paths:
      - 'mlops-platform/**'
jobs:
  test-components:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get required Python version
        id: get-python-version
        run: |
          required_python_version=$(./run.sh get_required_python_version)
          echo "required_python_version=$required_python_version" >> $GITHUB_OUTPUT
          echo "Required Python version: $required_python_version"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '${{ steps.get-python-version.outputs.required_python_version }}'

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev/requirements.txt

      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/mlops-platform
          pytest tests/
