name: Test Components

on:
  push:
    branches:
      - master
    paths:
      - 'mlops-platform/**'

permissions:
  contents: read # access to check out code and install dependencies

jobs:
  test-components:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
      # Ensure tests can import local package
      PYTHONPATH: ${{ github.workspace }}/mlops-platform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get required Python version
        id: get-python-version
        run: |
          required_python_version="$(./run.sh get_required_python_version)"
          if [[ -z "${required_python_version}" ]]; then
            echo "Could not determine Python version; defaulting to 3.11"
            required_python_version="3.11"
          fi
          echo "required_python_version=${required_python_version}" >> "$GITHUB_OUTPUT"
          echo "Using Python ${required_python_version}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '${{ steps.get-python-version.outputs.required_python_version }}'
          cache: 'pip'
          cache-dependency-path: |
            - dev/requirements.txt
            - pyproject.toml
            - poetry.lock

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev/requirements.txt

      - name: Run tests
        run: |
          pytest tests/
